version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      dotnet:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /src/App.GitHealth.Web
    schedule:
      interval: weekly
    groups:
      angular:
        patterns:
          - "@angular/*"
      npm-development:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /tests/App.GitHealth.E2E
    schedule:
      interval: weekly
    groups:
      end-to-end:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
