// <auto-generated />
using System;
using App.GitHealth.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.GitHealth.Api.Persistence.Migrations
{
    [DbContext(typeof(GitHealthDbContext))]
    partial class GitHealthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("App.GitHealth.Api.Persistence.Entities.AnalysisRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveUntilDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchNamespace")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CapturedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcludedPatternsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("InactiveAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedPatternsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceCommit")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "StartedAtUtc");

                    b.ToTable("AnalysisRuns", (string)null);
                });

            modelBuilder.Entity("App.GitHealth.Api.Persistence.Entities.BranchSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AheadCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AnalysisRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BehindCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommitId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastActivityAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipAuthor")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisRunId", "ReferenceName")
                        .IsUnique();

                    b.ToTable("BranchSnapshots", (string)null);
                });

            modelBuilder.Entity(
                "App.GitHealth.Api.Persistence.Entities.ContributorSnapshotEntity",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BranchSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CommitCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchSnapshotId", "Name", "Email")
                        .IsUnique();

                    b.ToTable("ContributorSnapshots", (string)null);
                });

            modelBuilder.Entity("App.GitHealth.Api.Persistence.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActiveUntilDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchNamespace")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcludedPatternsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InactiveAfterDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRepositoryAccessible")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LastSuccessfulAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedPatternsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceName")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LastSuccessfulAnalysisId");

                    b.HasIndex("RepositoryPath")
                        .IsUnique();

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("App.GitHealth.Api.Persistence.Entities.AnalysisRunEntity", b =>
                {
                    b.HasOne("App.GitHealth.Api.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany("AnalysisRuns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("App.GitHealth.Api.Persistence.Entities.BranchSnapshotEntity", b =>
                {
                    b.HasOne(
                            "App.GitHealth.Api.Persistence.Entities.AnalysisRunEntity",
                            "AnalysisRun")
                        .WithMany("Branches")
                        .HasForeignKey("AnalysisRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisRun");
                });

            modelBuilder.Entity(
                "App.GitHealth.Api.Persistence.Entities.ContributorSnapshotEntity",
                b =>
                {
                    b.HasOne(
                            "App.GitHealth.Api.Persistence.Entities.BranchSnapshotEntity",
                            "BranchSnapshot")
                        .WithMany("Contributors")
                        .HasForeignKey("BranchSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchSnapshot");
                });

            modelBuilder.Entity("App.GitHealth.Api.Persistence.Entities.AnalysisRunEntity", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("App.GitHealth.Api.Persistence.Entities.BranchSnapshotEntity", b =>
                {
                    b.Navigation("Contributors");
                });

            modelBuilder.Entity("App.GitHealth.Api.Persistence.Entities.ProjectEntity", b =>
                {
                    b.Navigation("AnalysisRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
